# Generated by Django 4.1.5 on 2023-01-29 13:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto_usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Canal_Comunicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecanal', models.CharField(max_length=25)),
                ('fecha_crecion_canal', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('estatus_canal', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='Abierto', max_length=15)),
                ('slug', models.SlugField(unique=True)),
                ('fk_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_usuario.registro_proyecto')),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canal_Comunicacion',
                'verbose_name_plural': 'Canales_Comunicacion',
                'db_table': 'Canal_Comunicacion',
            },
        ),
    ]
