# Generated by Django 4.1.5 on 2023-01-30 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modulo_comunicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes_canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajesCanal', to='modulo_comunicacion.canal_comunicacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajesCanal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
    ]
