# Generated by Django 4.1.5 on 2023-02-12 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_comunicacion', '0003_archivos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivos',
            options={'verbose_name': 'Archivo', 'verbose_name_plural': 'Archivos'},
        ),
        migrations.AlterModelTable(
            name='archivos',
            table='Arhivos',
        ),
    ]
