# Generated by Django 4.1.5 on 2023-02-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_comunicacion', '0007_alter_archivos_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivoprivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filegroup', models.FileField(upload_to='archivos/grupales')),
            ],
        ),
    ]
