# Generated by Django 4.1.5 on 2023-01-29 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='registro_proyecto',
            fields=[
                ('idproyecto', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False)),
                ('nombreproyecto', models.CharField(blank=True, max_length=50)),
                ('descripcionProyecto', models.CharField(max_length=80, null=True)),
                ('fechaincio', models.DateTimeField(auto_now_add=True)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'Proyecto',
            },
        ),
        migrations.CreateModel(
            name='conexionuser_proyec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto_usuario.registro_proyecto')),
                ('fk_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conexion',
                'verbose_name_plural': 'conexiones',
                'db_table': 'Conexion',
            },
        ),
    ]
